// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BackupAll():Promise<main.BackupResult>;

export function DeleteBackup(arg1:string):Promise<boolean>;

export function ExportSessions():Promise<string>;

export function GetBackups():Promise<Array<main.BackupInfo>>;

export function GetUserID():Promise<string>;

export function GetWorkspaceChats(arg1:string):Promise<Array<main.ChatInfo>>;

export function GetWorkspaces():Promise<Array<main.WorkspaceInfo>>;

export function OpenBackupFolder():Promise<string>;

export function RestoreBackup(arg1:string):Promise<main.RestoreResult>;
