// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupAll() {
  return window['go']['main']['App']['BackupAll']();
}

export function DeleteBackup(arg1) {
  return window['go']['main']['App']['DeleteBackup'](arg1);
}

export function ExportSessions() {
  return window['go']['main']['App']['ExportSessions']();
}

export function GetBackups() {
  return window['go']['main']['App']['GetBackups']();
}

export function GetUserID() {
  return window['go']['main']['App']['GetUserID']();
}

export function GetWorkspaceChats(arg1) {
  return window['go']['main']['App']['GetWorkspaceChats'](arg1);
}

export function GetWorkspaces() {
  return window['go']['main']['App']['GetWorkspaces']();
}

export function OpenBackupFolder() {
  return window['go']['main']['App']['OpenBackupFolder']();
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}
